name: run

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1,2,3,4,5"

jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - uses: pnpm/action-setup@v2
        with:
          version: 8.9.0
      - name: Install dependencies
        run: pnpm i
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run your tests
        run: JSL_ACCOUNT=${{ secrets.JSL_ACCOUNT }} JSL_SECRET=${{ secrets.JSL_SECRET }} app_token=${{ secrets.app_token }} table_id=${{ secrets.table_id }} app_id=${{ secrets.app_id }} app_secret=${{ secrets.app_secret }} npx playwright test
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report
